# Generated by Django 3.1.4 on 2021-01-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turnos',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manana'), (2, 'Tarde'), (3, 'Noche')], default=1),
            preserve_default=False,
        ),
    ]
